### ISSUE TITLE
Scrape bug

### ISSUE THREAD

**Issue by whatevernevermindbro** [celebi-pkg/flight-analysis#1]
Hi, Kaya!
The idea is awesome! I've been googling for Google Flights packages like API or scrapers and found yours.

But I've got the following bug while trying to reproduce the Quick Start example:

```
IndexError                                Traceback (most recent call last)
test.py in line 3
      22 # %%
      23 # Try to keep the dates in format YYYY-mm-dd
----> 24 result = Scrape('JFK', 'IST', '2023-05-20', '2023-06-10') # obtain our scrape object

File c:\Users\Alexander Levin\AppData\Local\Programs\Python\Python311\Lib\site-packages\google_flight_analysis\scrape.py:27, in _Scrape.__call__(self, *args)
     25 if len(args) == 4:
     26 	self._set_properties(*args)
---> 27 	self._data = self._scrape_data()
     28 	obj = self.clone()
     29 	obj.data = self._data

File c:\Users\Alexander Levin\AppData\Local\Programs\Python\Python311\Lib\site-packages\google_flight_analysis\scrape.py:114, in _Scrape._scrape_data(self)
    112 def _scrape_data(self):
    113 	url = self._make_url()
--> 114 	return self._get_results(url)

File c:\Users\Alexander Levin\AppData\Local\Programs\Python\Python311\Lib\site-packages\google_flight_analysis\scrape.py:131, in _Scrape._get_results(self, url)
    128 flight_info = _Scrape._get_info(results)
    129 partition = _Scrape._partition_info(flight_info)
--> 131 return _Scrape._parse_columns(partition, self._date_leave, self._date_return)

File c:\Users\Alexander Levin\AppData\Local\Programs\Python\Python311\Lib\site-packages\google_flight_analysis\scrape.py:238, in _Scrape._parse_columns(grouped, date_leave, date_return)
...
--> 238 i_diff += 1 if 'Separate tickets booked together' in g[2] else 0
    240 # Add airline, travel time, origin, and dest
    241 airline += [g[2 + i_diff]]

IndexError: list index out of range
```

The ```g``` variable is ```['12:30\u202fAM', 'JFK']``` at that point.

**Comment by kcelebi** [comment]
Thank you for bringing this up! The scraper is still a little buggy because it relies heavily on Selenium's ability to read through the JavaScript output. 

I'm working on improving the scraping functions to be a little cleaner, will update once this issue is fixed!

**Comment by whatevernevermindbro** [comment]
Hi @kcelebi,

That was actually a funny bug. So when Selenium opens up a new Chrome window on my Laptop, he opens it as a half-screen window. In that case, Google Flight adapts to the size like he is doing it when one opens the website from a tablet or a smartphone. Thus, he uses these _virtual dot_ separators (instead of regular commas), which don't exist in `.find_element().text.`

![image](https://user-images.githubusercontent.com/42086051/235821410-ff60d6cd-666c-4b52-8341-5bbae9e8ffe1.png)

Writing the line `driver.maximize_window()` right before `driver.get(url)` pretty much solves the problem.

**Comment by kcelebi** [comment]
This is a great piece of insight, thank you for figuring this out! I'll test and include this into the stack along with some other changes most likely by Saturday.

**Comment by Smyja** [comment]
> This is a great piece of insight, thank you for figuring this out! I'll test and include this into the stack along with some other changes most likely by Saturday.

great project

**Comment by kcelebi** [comment]
Version 1.1 out now, pushed the newest changes to the main branch. Let me know if any other issues come up!
