### ISSUE TITLE
sort error 

### ISSUE THREAD

**Issue by victorhugow** [celebi-pkg/flight-analysis#10]
Hey, Kaya!

First, thanks for your work with the lib! :)

I'm getting this error message when I try to run the example code

```
start = res2.index("Sort by:")+1
ValueError: 'Sort by:' is not in list
```

I apologize if this its a newbie kind of issue.

**Comment by kcelebi** [comment]
Hi, Victor! Thank you for pointing this out, this is definitely not a newbie error, more of a working issue on my end haha. I'll take a look and debug. Just to confirm, is it this query that you're running?

    Scrape('JFK', 'IST', '2023-07-20', '2023-08-10')

**Comment by victorhugow** [comment]
Yes, thats it!

**Comment by kcelebi** [comment]
Ok I think I was able to fix it. I'm currently developing some other features so I will include that fix along with those. If you want to use the unstable version now, you can access the test package (v1.1.1-alpha.3) through [here](https://test.pypi.org/project/google-flight-analysis/1.1.1a3/). 

This version uses a different methodology from what exists, though. Here's some example code to achieve what you're looking for:

    from google_flight_analysis.scrape import *
    # this creates a Scrape object which represents the query you're looking for
    result = Scrape("JFK", "IST", "2023-07-20", "2023-08-20")

    # we scrape the actual query here
    _ = ScrapeObjects(result)

    # The object has now been modified in-place to have the values you're looking for
    print(result)

    # Obtain the data
    print(result.data)




Closing issue for now, feel free to send an email/open another issue if the problem persists!
