### ISSUE TITLE
string to float error

### ISSUE THREAD

**Issue by Smyja** [celebi-pkg/flight-analysis#3]
when i run the example, i get this error.
```
price += [float(g[8 + i_diff][1:].replace(',',''))]
ValueError: could not convert string to float: 'GN 365873'
```

**Comment by kcelebi** [comment]
I've made a bunch of changes in the parser to fix this and some other errors. I will close this issue once v1.1.0 is released, which should be soon.

**Comment by Smyja** [comment]
> I've made a bunch of changes in the parser to fix this and some other errors. I will close this issue once v1.1.0 is released, which should be soon.

Great, I've fixed it on my end also.

**Comment by kcelebi** [comment]
Version 1.1 out now, pushed the newest changes to the main branch. Let me know if any other issues come up!
